import 'server-only'

import SupabaseProvider from './supabase-provider';
import { createClient } from '../utils/supabase-server';


import { Inter } from 'next/font/google';

import Providers from './components/Providers';
import './globals.css'
import Nav from './components/Nav';
import Menu from './components/Menu';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin' ]});

// do not cache this layout
export const revalidate = 0

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const supabase = createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <html
      lang='en'
      className={`bg-white dark:bg-slate-900 antialiased ${inter.className}`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className='text-slate-900 dark:text-slate-50 dark:bg-slate-900'
        >
        
        <Providers>
          <SupabaseProvider>
            <Nav />
            <main>{children}</main>
          </SupabaseProvider>
        </Providers>
      </body>
    </html>
  )
}
