import { Inter } from 'next/font/google';

import Providers from './components/Providers';
import './globals.css'
import Nav from './components/Nav';
import Menu from './components/Menu';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin' ]});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={`bg-white dark:bg-slate-900 antialiased ${inter.className}`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className='text-slate-900 dark:text-slate-50 dark:bg-slate-900'
        >
        <Providers>
          <Nav />
          {/* <Menu /> */}
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
