import { Inter } from 'next/font/google';

import Providers from './components/Providers';
import './globals.css'
import Nav from './components/Nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin' ]});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={`bg-white text-slate-900 antialiased ${inter.className}`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className=' bg-slate-50 dark:bg-slate-900'
        >
        <Providers>

          {/* @ts-expect-error Server Component */}
          <Nav />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
